[
  {
    _id: "675e9e70610619229c36252c",
    name: "Dr. Olivia Brown",
    username: "oliviabrown",
    fee: 150,
    type: "Allergists",
    phone: "+1-555-2468",
    email: "oliviabrown@gmail.com",
    address: "654 Allergy St, Denver, CO",
    image:
      "https://static.vecteezy.com/system/resources/previews/028/287/555/non_2x/an-indian-young-female-doctor-isolated-on-green-ai-generated-photo.jpg",
    country: "USA",
    dob: "1979-09-12",
    joining: 2006,
    rating: 4.7,
    verified: true,
    unavailableDates: [{ start: "2024-11-10", end: "2024-11-13" }],
    availability: [
      {
        days: ["Monday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "10:00", endTime: "12:00" }],
      },
    ],
    title: "Specialist in Allergy Management",
    gender: "Female",
    description:
      "Dr. Olivia Brown specializes in diagnosing and treating allergies with customized care plans to improve patient health and comfort.",
  },
  {
    _id: "675e9e70610619229c36252e",
    name: "Dr. Grace Anderson",
    username: "graceanderson",
    fee: 125,
    type: "Ophthalmologists",
    phone: "+1-555-7890",
    email: "graceanderson@gmail.com",
    address: "852 Vision Ave, Boston, MA",
    image:
      "https://www.canadaqbank.com/blog/storage/2022/05/How-to-become-a-doctor-in-USA.jpg",
    country: "USA",
    dob: "1987-10-05",
    joining: 2013,
    rating: 4.9,
    verified: true,
    unavailableDates: [{ start: "2024-12-10", end: "2024-12-15" }],
    availability: [
      {
        days: ["Monday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "08:00", endTime: "12:00" }],
      },
    ],
    title: "Eye Care Specialist",
    gender: "Female",
    description:
      "Dr. Grace Anderson provides advanced treatments for various eye conditions, ensuring optimal care and precision.",
  },
  {
    _id: "675e9e70610619229c362531",
    name: "Dr. Ethan Green",
    username: "ethangreen",
    fee: 140,
    type: "Allergists",
    phone: "+1-555-7531",
    email: "ethangreen@gmail.com",
    address: "258 Allergy Rd, Houston, TX",
    image:
      "https://static.vecteezy.com/system/resources/previews/049/696/510/non_2x/smiling-doctor-in-a-white-lab-coat-with-a-stethoscope-posing-confidently-indoors-free-photo.jpeg",
    country: "USA",
    dob: "1981-04-17",
    joining: 2008,
    rating: 4.7,
    verified: true,
    unavailableDates: [{ start: "2024-11-22", end: "2024-11-25" }],
    availability: [
      {
        days: ["Tuesday", "Wednesday", "Saturday"],
        timeSlots: [{ startTime: "14:00", endTime: "17:00" }],
      },
    ],
    title: "Specialist in Allergy Treatments",
    gender: "Male",
    description:
      "Dr. Ethan Green is dedicated to providing effective treatments for allergy symptoms, enhancing patient comfort and health.",
  },
  {
    _id: "675e9e70610619229c36253b",
    name: "Dr. Mark Turner",
    username: "markturner",
    fee: 125,
    type: "Neurologists",
    phone: "+1-555-7879",
    email: "markturner@gmail.com",
    address: "123 Brain Wellness St, Houston, TX",
    image:
      "https://st5.depositphotos.com/62628780/66002/i/1600/depositphotos_660023178-stock-photo-doctor-you-can-rely-cropped.jpg",
    country: "USA",
    dob: "1978-10-18",
    joining: 2004,
    rating: 4.6,
    verified: true,
    unavailableDates: [{ start: "2024-11-25", end: "2024-11-28" }],
    availability: [
      {
        days: ["Tuesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "09:00", endTime: "12:00" }],
      },
    ],
    title: "Neurology Expert",
    gender: "Male",
    description:
      "Dr. Mark Turner offers expert care for neurological conditions, ensuring optimal outcomes for patients.",
  },
  {
    _id: "675e9e70610619229c362532",
    name: "Dr. Sarah Miller",
    username: "sarahmiller",
    fee: 110,
    type: "Pediatricians",
    phone: "+1-555-1212",
    email: "sarahmiller@gmail.com",
    address: "123 Child Care Lane, San Diego, CA",
    image:
      "https://static.vecteezy.com/system/resources/previews/039/083/057/non_2x/doctor-beautiful-girl-smiling-portrait-in-yellow-uniform-with-a-stethoscope-near-the-window-health-care-background-photo.jpg",
    country: "USA",
    dob: "1986-03-10",
    joining: 2012,
    rating: 4.7,
    verified: true,
    unavailableDates: [{ start: "2024-11-15", end: "2024-11-18" }],
    availability: [
      {
        days: ["Monday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "10:00", endTime: "14:00" }],
      },
    ],
    title: "Experienced Pediatrician",
    gender: "Female",
    description:
      "Dr. Sarah Miller provides comprehensive care for children, ensuring their health and well-being.",
  },
  {
    _id: "675e9e70610619229c362533",
    name: "Dr. Robert Harris",
    username: "robertharris",
    fee: 150,
    type: "Orthopedic Surgeons",
    phone: "+1-555-3434",
    email: "robertharris@gmail.com",
    address: "456 Bone Care Blvd, Dallas, TX",
    image:
      "https://i.pinimg.com/736x/f4/c9/ef/f4c9ef33d04a22050038e9e53eeb7d85.jpg",
    country: "USA",
    dob: "1977-05-23",
    joining: 2003,
    rating: 4.8,
    verified: true,
    unavailableDates: [{ start: "2024-12-05", end: "2024-12-10" }],
    availability: [
      {
        days: ["Tuesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "09:00", endTime: "12:00" }],
      },
    ],
    title: "Orthopedic Specialist",
    gender: "Male",
    description:
      "Dr. Robert Harris is a leading orthopedic surgeon with years of expertise in joint and bone care.",
  },
  {
    _id: "675e9e70610619229c362534",
    name: "Dr. Anna Clark",
    username: "annaclark",
    fee: 120,
    type: "Gastroenterologists",
    phone: "+1-555-5656",
    email: "annaclark@gmail.com",
    address: "789 Digestive Health St, Seattle, WA",
    image:
      "https://static8.depositphotos.com/1177973/907/i/950/depositphotos_9076416-stock-photo-beautiful-girl-doctor-in-the.jpg",
    country: "USA",
    dob: "1982-07-11",
    joining: 2010,
    rating: 4.6,
    verified: true,
    unavailableDates: [{ start: "2024-12-20", end: "2024-12-25" }],
    availability: [
      {
        days: ["Monday", "Thursday", "Friday"],
        timeSlots: [{ startTime: "11:00", endTime: "15:00" }],
      },
    ],
    title: "Expert in Digestive Health",
    gender: "Female",
    description:
      "Dr. Anna Clark specializes in diagnosing and treating digestive disorders with personalized care.",
  },
  {
    _id: "675e9e70610619229c362536",
    name: "Dr. Laura Wilson",
    username: "laurawilson",
    fee: 115,
    type: "Dermatologists",
    phone: "+1-555-9090",
    email: "laurawilson@gmail.com",
    address: "654 Skin Wellness Dr, Orlando, FL",
    image:
      "https://media.istockphoto.com/id/1267013330/photo/portrait-of-a-confident-young-female-doctor-at-work.jpg?s=612x612&w=0&k=20&c=_E-ImNGq8ZRzCq3QcKxDjXtk3OWPOvMqzddjGzlad9U=",
    country: "USA",
    dob: "1988-02-25",
    joining: 2015,
    rating: 4.5,
    verified: true,
    unavailableDates: [{ start: "2024-11-10", end: "2024-11-14" }],
    availability: [
      {
        days: ["Monday", "Tuesday", "Friday"],
        timeSlots: [{ startTime: "09:00", endTime: "13:00" }],
      },
    ],
    title: "Skin Care Expert",
    gender: "Female",
    description:
      "Dr. Laura Wilson is dedicated to enhancing skin health with personalized and effective treatments.",
  },
  {
    _id: "675e9e70610619229c362528",
    name: "Dr. Emily Johnson",
    username: "emilyjohnson",
    fee: 120,
    type: "Cardiologists",
    phone: "+1-555-6789",
    email: "emilyjohnson@gmail.com",
    address: "789 Care St, San Francisco, CA",
    image:
      "https://media.istockphoto.com/id/1189304032/photo/doctor-holding-digital-tablet-at-meeting-room.jpg?s=612x612&w=0&k=20&c=RtQn8w_vhzGYbflSa1B5ea9Ji70O8wHpSgGBSh0anUg=",
    country: "USA",
    dob: "1982-02-14",
    joining: 2009,
    rating: 4.3,
    verified: true,
    unavailableDates: [{ start: "2024-12-20", end: "2024-12-25" }],
    availability: [
      {
        days: ["Monday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "09:00", endTime: "12:00" }],
      },
    ],
    title: "Experienced Heart Care Specialist",
    gender: "Female",
    description:
      "Dr. Emily Johnson is a highly skilled cardiologist with over 15 years of experience treating heart conditions. She specializes in providing personalized care to patients with cardiovascular issues.",
  },
  {
    _id: "675e9e70610619229c36252a",
    name: "Dr. Sophia Martinez",
    username: "sophiamartinez",
    fee: 140,
    type: "Endocrinologists",
    phone: "+1-555-9876",
    email: "sophiamartinez@gmail.com",
    address: "321 Wellness Ave, Austin, TX",
    image:
      "https://www.shutterstock.com/image-photo/medical-concept-indian-beautiful-female-600nw-1635029716.jpg",
    country: "USA",
    dob: "1985-08-15",
    joining: 2011,
    rating: 4.5,
    verified: true,
    unavailableDates: [{ start: "2024-11-15", end: "2024-11-20" }],
    availability: [
      {
        days: ["Monday", "Tuesday", "Friday"],
        timeSlots: [{ startTime: "14:00", endTime: "18:00" }],
      },
    ],
    title: "Specialist in Hormonal Disorders",
    gender: "Female",
    description:
      "Dr. Sophia Martinez focuses on diagnosing and managing hormonal imbalances and endocrine disorders, offering tailored treatments for each patient.",
  },
  {
    _id: "675e9e70610619229c36252d",
    name: "Dr. Daniel White",
    username: "danielwhite",
    fee: 110,
    type: "Cardiologists",
    phone: "+1-555-6543",
    email: "danielwhite@gmail.com",
    address: "147 Heart St, Seattle, WA",
    image:
      "https://cdn.pixabay.com/photo/2024/09/03/15/21/ai-generated-9019520_640.png",
    country: "USA",
    dob: "1975-05-18",
    joining: 2004,
    rating: 4.4,
    verified: true,
    unavailableDates: [{ start: "2024-11-25", end: "2024-11-30" }],
    availability: [
      {
        days: ["Tuesday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "13:00", endTime: "16:00" }],
      },
    ],
    title: "Heart Specialist with Experience",
    gender: "Male",
    description:
      "Dr. Daniel White has extensive expertise in diagnosing and managing cardiovascular diseases with a patient-focused approach.",
  },
  {
    _id: "675e9e70610619229c362538",
    name: "Dr. Rachel Adams",
    username: "racheladams",
    fee: 125,
    type: "Pediatricians",
    phone: "+1-555-3433",
    email: "racheladams@gmail.com",
    address: "852 Child Health Ave, New York, NY",
    image:
      "https://www.shutterstock.com/image-photo/smiling-young-african-american-curly-600nw-2319779015.jpg",
    country: "USA",
    dob: "1985-09-19",
    joining: 2011,
    rating: 4.8,
    verified: true,
    unavailableDates: [{ start: "2024-12-01", end: "2024-12-05" }],
    availability: [
      {
        days: ["Monday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "08:00", endTime: "12:00" }],
      },
    ],
    title: "Children's Health Specialist",
    gender: "Female",
    description:
      "Dr. Rachel Adams is passionate about providing quality health care for children.",
  },
  {
    _id: "675e9e70610619229c362539",
    name: "Dr. Brian King",
    username: "brianking",
    fee: 145,
    type: "Orthopedic Surgeons",
    phone: "+1-555-5657",
    email: "brianking@gmail.com",
    address: "963 Joint Care Rd, Chicago, IL",
    image:
      "https://thumbs.dreamstime.com/b/young-male-doctor-close-up-happy-looking-camera-56751540.jpg",
    country: "USA",
    dob: "1979-06-30",
    joining: 2006,
    rating: 4.7,
    verified: true,
    unavailableDates: [{ start: "2024-12-15", end: "2024-12-20" }],
    availability: [
      {
        days: ["Tuesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "10:00", endTime: "13:00" }],
      },
    ],
    title: "Orthopedic Specialist",
    gender: "Male",
    description:
      "Dr. Brian King focuses on treating bone and joint disorders with advanced techniques.",
  },
  {
    _id: "675e9e70610619229c362529",
    name: "Dr. Michael Carter",
    username: "michaelcarter",
    fee: 100,
    type: "Ophthalmologists",
    phone: "+1-555-4567",
    email: "michaelcarter@gmail.com",
    address: "456 Vision Blvd, Los Angeles, CA",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/041/408/858/small_2x/ai-generated-a-smiling-doctor-with-glasses-and-a-white-lab-coat-isolated-on-transparent-background-free-png.png",
    country: "USA",
    dob: "1978-06-21",
    joining: 2005,
    rating: 4.8,
    verified: true,
    unavailableDates: [{ start: "2024-12-22", end: "2024-12-27" }],
    availability: [
      {
        days: ["Tuesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "10:00", endTime: "13:00" }],
      },
    ],
    title: "Expert in Eye Care Solutions",
    gender: "Male",
    description:
      "Dr. Michael Carter has been providing exceptional eye care for over 20 years. He is dedicated to diagnosing and treating a wide range of eye disorders with advanced techniques.",
  },
  {
    _id: "675e9e70610619229c36252b",
    name: "Dr. David Lee",
    username: "davidlee",
    fee: 130,
    type: "Dermatologists",
    phone: "+1-555-1234",
    email: "davidlee@gmail.com",
    address: "987 Skin Care Rd, Miami, FL",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/026/375/249/small_2x/ai-generative-portrait-of-confident-male-doctor-in-white-coat-and-stethoscope-standing-with-arms-crossed-and-looking-at-camera-photo.jpg",
    country: "USA",
    dob: "1980-03-22",
    joining: 2007,
    rating: 4.6,
    verified: true,
    unavailableDates: [{ start: "2024-12-01", end: "2024-12-05" }],
    availability: [
      {
        days: ["Wednesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "11:00", endTime: "15:00" }],
      },
    ],
    title: "Expert in Skin Health",
    gender: "Male",
    description:
      "Dr. David Lee offers comprehensive care for a variety of skin conditions, using advanced techniques and personalized treatments.",
  },
  {
    _id: "675e9e70610619229c36252f",
    name: "Dr. James Collins",
    username: "jamescollins",
    fee: 135,
    type: "Endocrinologists",
    phone: "+1-555-2460",
    email: "jamescollins@gmail.com",
    address: "963 Endo St, Chicago, IL",
    image:
      "https://t4.ftcdn.net/jpg/02/60/04/09/360_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
    country: "USA",
    dob: "1983-07-28",
    joining: 2010,
    rating: 4.5,
    verified: true,
    unavailableDates: [{ start: "2024-11-28", end: "2024-12-02" }],
    availability: [
      {
        days: ["Tuesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "12:00", endTime: "16:00" }],
      },
    ],
    title: "Expert in Metabolic Disorders",
    gender: "Male",
    description:
      "Dr. James Collins has years of experience treating metabolic and endocrine disorders with evidence-based care.",
  },
  {
    _id: "675e9e70610619229c362530",
    name: "Dr. Lily Adams",
    username: "lilyadams",
    fee: 120,
    type: "Dermatologists",
    phone: "+1-555-3698",
    email: "lilyadams@gmail.com",
    address: "741 Skin Care Blvd, Phoenix, AZ",
    image:
      "https://img.freepik.com/free-photo/woman-doctor-wearing-lab-coat-with-stethoscope-isolated_1303-29791.jpg",
    country: "USA",
    dob: "1984-11-11",
    joining: 2009,
    rating: 4.6,
    verified: true,
    unavailableDates: [{ start: "2024-11-18", end: "2024-11-21" }],
    availability: [
      {
        days: ["Monday", "Thursday", "Friday"],
        timeSlots: [{ startTime: "09:00", endTime: "13:00" }],
      },
    ],
    title: "Dermatology Expert",
    gender: "Female",
    description:
      "Dr. Lily Adams excels in treating various skin conditions, ensuring her patients achieve healthy and glowing skin.",
  },
  {
    _id: "675e9e70610619229c362535",
    name: "Dr. Thomas Evans",
    username: "thomasevans",
    fee: 140,
    type: "Neurologists",
    phone: "+1-555-7878",
    email: "thomasevans@gmail.com",
    address: "321 Neuro Health Ave, Denver, CO",
    image:
      "https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg",
    country: "USA",
    dob: "1975-08-08",
    joining: 2005,
    rating: 4.9,
    verified: true,
    unavailableDates: [{ start: "2024-11-28", end: "2024-12-01" }],
    availability: [
      {
        days: ["Wednesday", "Thursday", "Saturday"],
        timeSlots: [{ startTime: "14:00", endTime: "18:00" }],
      },
    ],
    title: "Brain and Nerve Specialist",
    gender: "Male",
    description:
      "Dr. Thomas Evans provides expert care for neurological disorders, focusing on patient recovery and well-being.",
  },
  {
    _id: "675e9e70610619229c362537",
    name: "Dr. William Taylor",
    username: "williamtaylor",
    fee: 130,
    type: "Allergists",
    phone: "+1-555-1235",
    email: "williamtaylor@gmail.com",
    address: "741 Allergy Relief St, Boston, MA",
    image:
      "https://t4.ftcdn.net/jpg/07/07/89/33/360_F_707893394_5DEhlBjWOmse1nyu0rC9T7ZRvsAFDkYC.jpg",
    country: "USA",
    dob: "1980-04-14",
    joining: 2008,
    rating: 4.6,
    verified: true,
    unavailableDates: [{ start: "2024-11-15", end: "2024-11-18" }],
    availability: [
      {
        days: ["Tuesday", "Wednesday", "Saturday"],
        timeSlots: [{ startTime: "13:00", endTime: "16:00" }],
      },
    ],
    title: "Allergy Specialist",
    gender: "Male",
    description:
      "Dr. William Taylor specializes in allergy treatments to improve patient quality of life.",
  },
  {
    _id: "675e9e70610619229c36253a",
    name: "Dr. Megan Lopez",
    username: "meganlopez",
    fee: 135,
    type: "Gastroenterologists",
    phone: "+1-555-9091",
    email: "meganlopez@gmail.com",
    address: "258 Digestive Health Blvd, Phoenix, AZ",
    image:
      "https://img.freepik.com/free-photo/female-doctor-hospital-with-stethoscope_23-2148827776.jpg",
    country: "USA",
    dob: "1983-03-05",
    joining: 2009,
    rating: 4.5,
    verified: true,
    unavailableDates: [{ start: "2024-12-10", end: "2024-12-15" }],
    availability: [
      {
        days: ["Monday", "Thursday", "Friday"],
        timeSlots: [{ startTime: "14:00", endTime: "18:00" }],
      },
    ],
    title: "Digestive Health Specialist",
    gender: "Female",
    description:
      "Dr. Megan Lopez specializes in managing digestive disorders with personalized treatments.",
  },
  {
    _id: "675f37b232e6e3699fa6719c",
    name: "Dr. Emma Thompson",
    username: "emmathompson",
    fee: 120,
    type: "Ophthalmologists",
    phone: "+1-555-7890",
    email: "emmathompson@gmail.com",
    address: "789 Clearview Road, New York, NY",
    image:
      "https://media.istockphoto.com/id/638647058/photo/we-offer-our-patients-premium-healthcare-here.jpg?s=612x612&w=0&k=20&c=pek5ehwgsZNPemeEh4bObQ1U5DRPEs0WHleosG-daa8=",
    country: "USA",
    dob: "1985-03-14",
    joining: 2012,
    rating: 4.9,
    verified: true,
    unavailableDates: [{ start: "2024-12-25", end: "2024-12-31" }],
    availability: [
      {
        days: ["Monday", "Wednesday", "Friday"],
        timeSlots: [{ startTime: "09:00", endTime: "12:00" }],
      },
    ],
    title: "Renowned Specialist in Vision Health",
    gender: "Female",
    description:
      "Dr. Emma Thompson is a highly skilled ophthalmologist with a decade of experience in advanced eye care, committed to delivering personalized and effective treatments.",
  },

  {
    _id: "67612353754dade1fa8121e9",
    name: "ahsan",
    email: "d@d.com",
    image:
      "https://media.licdn.com/dms/image/v2/D5635AQEI-V9xrIYK2Q/profile-framedphoto-shrink_400_400/profile-framedphoto-shrink_400_400/0/1725219556560?e=1735027200&v=beta&t=6WjfH2CG9Du8AhpT3cF9sb6NS1m3ABENf0s_JKD873A",
    type: "Endocrinologists",
    verified: false,
    role: "doctor",
    createdAt: "2024-12-17T07:08:03.301Z",
  },
];
